---
title: "GLOBIO_10arcsec_check_19022026"
author: "Emmanuel Oceguera" "Andres Marmol"
date: "2026-02-19"
output: html_document
---

```{r}
library(ebvcube)
library(terra)
```

## Listing all new created .nc files
```{r}
rm(list = ls())

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
root <- '../Data_geo/'

nc_files <- list.files(
  path = root,
  pattern = "\\.nc$",
  recursive = TRUE,
  full.names = TRUE,
  ignore.case = TRUE
)

print(nc_files)

#to simplify names

```


# 1. GLOBIO land use projections high resolution

```{r}
globio2 <- ebv_properties(nc_files[2], verbose=FALSE)
print(globio2)

```

```{r}
slotNames(globio2)
```

### cube paths to see metric names and descriptions

```{r}
globiopaths <- ebv_datacubepaths(nc_files[2], verbose = FALSE)
globiopaths
```

```{r}
globio_dc <- ebv_properties(nc_files[2], globiopaths[1,1], verbose=FALSE)
globio_dc@metric
```

```{r}
globio <- ebv_properties(nc_files[2],  verbose=FALSE)
globio@general$entity_names
```
### Temporal and spatial resolution
```{r}
# Spatial 
cat("EPSG: ", globio@spatial$epsg, "\n")
cat("Resolution: ", globio@spatial$resolution, "\n")
cat("Extent: ", globio@spatial$extent, "\n")

# Temporal
cat("Dates: ", as.character(globio@temporal$dates))
```

### datatype
```{r}
# Datatype
globio_dc@ebv_cube$type
```

### plot: Not yet possible for GLOBIO
```{r}
datacube_path <- ebv_datacubepaths(nc_files[2])
dc <- datacube_path[1,1]

start.time <- Sys.time()
data <- ebv_read(nc_files[2], dc, entity = 5, timestep = 1:1, type = 'r', ignore_RAM = TRUE)
end.time <- Sys.time()

time.taken <- end.time - start.time
time.taken

plot(data)
```