---
title: "GLOBIO_0.5_check_19022026"
author: ["Emmanuel Oceguera", "Andres Marmol"]
date: "2026-02-19"
output: html_document
---

```{r}
library(ebvcube)
library(terra)
```

## Listing all new created .nc files

```{r}
rm(list = ls())

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
root <- '../Data_geo/'

nc_files <- list.files(
  path = root,
  pattern = "\\.nc$",
  recursive = TRUE,
  full.names = TRUE,
  ignore.case = TRUE
)

print(nc_files)
```

# 1 GLOBIO Land use projections upscale 0.5.

### general properties

```{r}
globio05 <- ebv_properties(nc_files[1], verbose=FALSE)
cat("GLOBIO Land use projections 10 arc sec. \n")
print(globio05)
```

```{r}
slotNames(globio05)
```

### cube paths to see metric names and descriptions

```{r}
globiopaths <- ebv_datacubepaths(nc_files[1], verbose = FALSE)
globiopaths

```

```{r}
globio_dc <- ebv_properties(nc_files[1], globiopaths[1,1], verbose=FALSE)
globio_dc@metric
```

### spatial and temporal resolution

```{r}
# Spatial 
cat("EPSG: ", globio05@spatial$epsg, "\n")
cat("Resolution: ", globio05@spatial$resolution, "\n")
cat("Extent: ", globio05@spatial$extent, "\n")

# Temporal
cat("Dates: ", as.character(globio05@temporal$dates))
```

### datatype

```{r}
# Datatype
globio_dc@ebv_cube$type
```

```{r}
globio <- ebv_properties(nc_files[1],  verbose=FALSE)
globio@general$entity_names
```

```{r}
datacube_path <- ebv_datacubepaths(nc_files[1])
dc <- datacube_path[2,1]
nfnrast <- ebv_read(nc_files[1], dc, entity = 9, timestep = 3, type = 'r')

plot(nfnrast)
```

### calling rasters to create plots (these is beyond the tutorial)

```{r}
# nfn
dc <- datacube_path[1,1]
nfnrast <- ebv_read(nc_files[1], dc, entity = 2, timestep = 3, type = 'r')

#nac
dc <- datacube_path[2,1]
nacrast <- ebv_read(nc_files[1], dc, entity = 2, timestep = 3, type = 'r')

#nfs
dc <- datacube_path[3,1]
nfsrast <- ebv_read(nc_files[1], dc, entity = 2, timestep = 3, type = 'r')

#BAU
dc <- datacube_path[4,1]
baurast <- ebv_read(nc_files[1], dc, entity = 2, timestep = 3, type = 'r')
```

# Plotting in GGPLOT

```{r}
library(cowplot)
library(tidyterra)
library(ggplot2)
library(patchwork)
```

```{r}

a <- ggplot()+
  geom_spatraster(data = nfnrast)+
  scale_fill_viridis_c(option = "magma", na.value="white")+
  #scale_fill_distiller(palette = "magma", direction = 1, na.value = "white")+
  coord_sf(expand = FALSE) +
  theme_minimal()+
  ggtitle("NfN")+
  theme(
    panel.grid = element_blank(),
    plot.margin = margin(2, 2, 2, 2),
    axis.title = element_blank(),
    axis.line = element_line(),
    axis.ticks = element_line(),
    axis.text = element_text(size = 8))
  #theme_minimal()

b <- ggplot()+
  geom_spatraster(data = nfsrast)+
  scale_fill_viridis_c(option = "magma", na.value="white")+
  #scale_fill_distiller(palette = "magma", direction = 1, na.value = "white")+
  coord_sf(expand = FALSE) +
  theme_minimal()+
  ggtitle("NfS")+
  theme(
    panel.grid = element_blank(),
    plot.margin = margin(2, 2, 2, 2),
    axis.title = element_blank(),
    axis.line = element_line(),
    axis.ticks = element_line(),
    axis.text = element_text(size = 8))

c <- ggplot()+
  geom_spatraster(data = nacrast)+
  scale_fill_viridis_c(option = "magma", na.value="white")+
  #scale_fill_distiller(palette = "magma", direction = 1, na.value = "white")+
  coord_sf(expand = FALSE) +
  theme_minimal()+
  ggtitle("NaC")+
  theme(
    panel.grid = element_blank(),
    plot.margin = margin(2, 2, 2, 2),
    axis.title = element_blank(),
    axis.line = element_line(),
    axis.ticks = element_line(),
    axis.text = element_text(size = 8))

d <- ggplot()+
  geom_spatraster(data = baurast)+
  scale_fill_viridis_c(option = "magma", na.value="white")+
  #scale_fill_distiller(palette = "magma", direction = 1, na.value = "white")+
  coord_sf(expand = FALSE) +
  theme_minimal()+
  ggtitle("BAU")+
  theme(
    panel.grid = element_blank(),
    plot.margin = margin(2, 2, 2, 2),
    axis.title = element_blank(),
    axis.line = element_line(),
    axis.ticks = element_line(),
    axis.text = element_text(size = 8))

legend <- get_legend(
  a+theme(legend.position = "right")
)

anl <- a + theme(legend.position = "none")
bnl <- b + theme(legend.position = "none")
cnl <- c + theme(legend.position = "none")
dnl <- d + theme(legend.position = "none")

#complot <- (anl + bnl) / (cnl + dnl) +
#  plot_layout(guides = "collect") & theme (legend.position = "right")

complot <- plot_grid(
  anl, bnl, cnl, dnl,
  nrow = 2,
  ncol = 2
  #labels = c("NfN 2050", "NfS 2050")
)

complot
```

```{r}
ggsave(complot, file="cropland_2050_nfn-nfs_GLOBIO.jpg", width = 10, height = 7)
```

```{r}
plot(nacrast - nfsrast)
```


