---
title: "PLUM_0.5_check_id102"
author: "Andres Marmol"
date: "2026-02-19"
output: html_document
---

```{r}
library(ebvcube)
library(terra)
```

## Listing all new created .nc files
```{r}
rm(list = ls())

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
root <- '../Data_geo/'

nc_files <- list.files(
  path = root,
  pattern = "\\.nc$",
  recursive = TRUE,
  full.names = TRUE,
  ignore.case = TRUE
)

print(nc_files)

#to simplify names

```

#  PLUM land use projection 0.01 degrees

```{r}
plum <- ebv_properties(nc_files[5], verbose=FALSE)
print(plum)

```

```{r}
slotNames(plum)
```

### cube paths to see metric names and descriptions

```{r}
plumpaths <- ebv_datacubepaths(nc_files[6], verbose = FALSE)
plumpaths
```

### change plumpaths number to check other metrics
```{r}
plum_dc <- ebv_properties(nc_files[6], plumpaths[1,1], verbose=FALSE)
plum_dc@metric
```

### spatial and temporal resolution
```{r}
# Spatial 
cat("EPSG: ", plum@spatial$epsg, "\n")
cat("Resolution: ", plum@spatial$resolution, "\n")
cat("Extent: ", plum@spatial$extent, "\n")

# Temporal
cat("Dates: ", as.character(plum@temporal$dates))
```
### data type
```{r}
# Datatype
plum_dc@ebv_cube$typ
```

```{r}
plum <- ebv_properties(nc_files[5],  verbose=FALSE)
plum@general$entity_names
```

```{r}
datacube_path <- ebv_datacubepaths(nc_files[5])
dc <- datacube_path[12,1]

start.time <- Sys.time()
nfnrast <- ebv_read(nc_files[5], dc, entity = 5, timestep = 1:4, type = 'r')
end.time <- Sys.time()

time.taken <- end.time - start.time
time.taken

# Plot data
a = plot(nfnrast)
```
### calling al rasters and then summing protected and unprotected (beyond tutorial)

```{r}
start.time <- Sys.time()

#nfn
dc <- datacube_path[1,1]
nfnrastun <- ebv_read(nc_files[5], dc, entity = 9, timestep = 3, type = 'r')
dc <- datacube_path[2,1]
nfnrastp <- ebv_read(nc_files[5], dc, entity = 9, timestep = 3, type = 'r')

#nac
dc <- datacube_path[6,1]
nacrastun <- ebv_read(nc_files[5], dc, entity = 9, timestep = 3, type = 'r')
dc <- datacube_path[5,1]
nacrastp <- ebv_read(nc_files[5], dc, entity = 9, timestep = 3, type = 'r')

#nfs
dc <- datacube_path[8,1]
nfsrastun <- ebv_read(nc_files[5], dc, entity = 9, timestep = 3, type = 'r')
dc <- datacube_path[7,1]
nfsrastp <- ebv_read(nc_files[5], dc, entity = 9, timestep = 3, type = 'r')

#BAU
dc <- datacube_path[10,1]
baurastun <- ebv_read(nc_files[5], dc, entity = 9, timestep = 3, type = 'r')
dc <- datacube_path[9,1]
baurastp <- ebv_read(nc_files[5], dc, entity = 9, timestep = 3, type = 'r')

# Summing rasters

nfnrast <- (nfnrastun + nfnrastp)
nacrast <- nacrastun + nacrastp
nfsrast <- nfsrastun + nfsrastp
baurast <- baurastun + baurastp

end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
```

### ploting 

```{r}
library(cowplot)
library(tidyterra)
library(ggplot2)
```

```{r}

a <- ggplot()+
  geom_spatraster(data = nfnrast)+
  scale_fill_viridis_c(option = "magma", na.value="white")+
  #scale_fill_distiller(palette = "magma", direction = 1, na.value = "white")+
  coord_sf(expand = FALSE) +
  theme_minimal()+
  ggtitle("NfN")+
  theme(
    panel.grid = element_blank(),
    plot.margin = margin(2, 2, 2, 2),
    axis.title = element_blank(),
    axis.line = element_line(),
    axis.ticks = element_line(),
    axis.text = element_text(size = 8))
  #theme_minimal()

b <- ggplot()+
  geom_spatraster(data = nfsrast)+
  scale_fill_viridis_c(option = "magma", na.value="white")+
  #scale_fill_distiller(palette = "magma", direction = 1, na.value = "white")+
  coord_sf(expand = FALSE) +
  theme_minimal()+
  ggtitle("NfS")+
  theme(
    panel.grid = element_blank(),
    plot.margin = margin(2, 2, 2, 2),
    axis.title = element_blank(),
    axis.line = element_line(),
    axis.ticks = element_line(),
    axis.text = element_text(size = 8))

c <- ggplot()+
  geom_spatraster(data = nacrast)+
  scale_fill_viridis_c(option = "magma", na.value="white")+
  #scale_fill_distiller(palette = "magma", direction = 1, na.value = "white")+
  coord_sf(expand = FALSE) +
  theme_minimal()+
  ggtitle("NaC")+
  theme(
    panel.grid = element_blank(),
    plot.margin = margin(2, 2, 2, 2),
    axis.title = element_blank(),
    axis.line = element_line(),
    axis.ticks = element_line(),
    axis.text = element_text(size = 8))

d <- ggplot()+
  geom_spatraster(data = baurast)+
  scale_fill_viridis_c(option = "magma", na.value="white")+
  #scale_fill_distiller(palette = "magma", direction = 1, na.value = "white")+
  coord_sf(expand = FALSE) +
  theme_minimal()+
  ggtitle("BAU")+
  theme(
    panel.grid = element_blank(),
    plot.margin = margin(2, 2, 2, 2),
    axis.title = element_blank(),
    axis.line = element_line(),
    axis.ticks = element_line(),
    axis.text = element_text(size = 8))

legend <- get_legend(
  a+theme(legend.position = "right")
)

anl <- a + theme(legend.position = "none")
bnl <- b + theme(legend.position = "none")
cnl <- c + theme(legend.position = "none")
dnl <- d + theme(legend.position = "none")

complot <- plot_grid(
  anl, bnl, cnl, dnl,
  nrow = 2,
  ncol = 2
  #labels = c("NfN 2050", "NfS 2050")
)

#complot <- plot_grid(
#  complot, legend,
#  nrow = 1,
#  rel_widths = c (1, 0.98)
#)

complot
```

```{r}
ggsave(complot, file="unmanforest_2050_nfn-nfs.jpg", width = 10, height = 7)
```

```{r}
plot(nfnrast$lyr.3-nfnrast$lyr.1)
```

